os:
  - linux
  - osx
language: c
sudo: false
compiler:
  - gcc
  - clang
before_install:
  - pip install --user codecov
  - pip install --user cpp-coveralls --use-mirrors
script: 
  - ./configure --with-gcov && make && make test
after_failure:
  - cat test/test-suite.log
after_script:
  - codecov
  - coveralls
addons:
  coverity_scan:
    project:
      name: "nijel/enca"
      description: "Build submitted via Travis CI"
    notification_email: michal@cihar.com
    build_command_prepend: "./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
  apt:
    packages:
    - librecode-dev
matrix:
  exclude:
    - os: osx
      compiler: gcc
